apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{TOPIC_NAME}}
  labels:
    strimzi.io/cluster: strimzi-kafka-cluster
spec:
  partitions: {{PARTITIONS}}
  replicas: {{REPLICAS}}
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
