## Statically define one or more cluster
clusters: {}
## Ex)
#clusters:
#  - name: "default"
#    bootstrapBrokers: "simple-strimzi-kafka-bootstrap.strimzi.svc.cluster.local:9092"
#    # Properties defined by org.apache.kafka.clients.consumer.ConsumerConfig
#    # can be defined in this configuration section.
#    # https://kafka.apache.org/documentation/#consumerconfigs
#    consumerProperties:
#      security.protocol: SSL
#      ssl.truststore.location: /path/to/my.truststore.jks
#      ssl.trustore.password: mypwd
#    # https://kafka.apache.org/documentation/#adminclientconfigs
#    adminClientProperties:
#      security.protocol: SSL
#      ssl.truststore.location: /path/to/my.truststore.jks
#      ssl.trustore.password: mypwd

## The interval between refreshing metrics
pollIntervalSeconds: 30
## Size of the sliding window of offsets to keep in each partition's lookup table
lookupTableSize: 60
## The Consumer Group `group.id` to use when connecting to Kafka
clientGroupId: "kafkalagexporter"
## The timeout when communicating with Kafka clusters
kafkaClientTimeoutSeconds: 10
## Watchers will automatically discover and forget Kafka clusters
watchers:
  ## The Strimzi Cluster Watcher automatically watches for `kafka.strimzi.io` group, `Kafka` kind resources and will
  ## configure the Kafka Lag Exporter appropriately.
  strimzi: false

## The log level of the ROOT logger
rootLogLevel: INFO
## The log level of Kafka Lag Exporter
kafkaLagExporterLogLevel: INFO
## The log level of `org.apache.kafka` logger
kafkaLogLevel: INFO
## The log level of Akka
akkaLogLevel: DEBUG

## You probably won't need to change anything below this line.
image:
  repository: lightbend/kafka-lag-exporter
  tag: 0.5.1-SNAPSHOT
  pullPolicy: Always
service:
  type: ClusterIP
  port: 8000
resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}
